#!/usr/bin/env python

from detectron2.config import CfgNode as CN
from detectron2_timm.config.defaults import _C as _c


_C = _c.clone()
# resnet layers for modified resnet architecture
_C.MODEL.RESNETS.LAYERS = [3, 4, 6, 3]

# roi heads
_C.MODEL.ROI_HEADS.USE_DROPLOSS = False
_C.MODEL.ROI_HEADS.DROPLOSS_IOU_THRESH = 0.0

# clip params
_C.MODEL.CLIP = CN()
_C.MODEL.CLIP.ARCHITECTURE = ''
_C.MODEL.CLIP.TOPK = 5
_C.MODEL.CLIP.PROB_SCALE = 100.0
_C.MODEL.CLIP.CROP_SCALE = 1.2
_C.MODEL.CLIP.EVAL_ONLY = True
_C.MODEL.CLIP.HALF_FLOAT = False  # half precision floating point

_C.MODEL.CLIP.TEXT_ENCODER = CN()
_C.MODEL.CLIP.TEXT_ENCODER.FROZEN = False
_C.MODEL.CLIP.TEXT_ENCODER.VOCAB_SIZE = 49408
_C.MODEL.CLIP.TEXT_ENCODER.CONTEXT_LENGTH = 77  # positional embedding length
_C.MODEL.CLIP.TEXT_ENCODER.EMBED_DIM = 1024
_C.MODEL.CLIP.TEXT_ENCODER.TRANSFORMER_WIDTH = 512
_C.MODEL.CLIP.TEXT_ENCODER.TRANSFORMER_LAYERS = 12
_C.MODEL.CLIP.TEXT_ENCODER.TRANSFORMER_HEADS = 8

_C.MODEL.CLIP.IMAGE_ENCODER = CN()
_C.MODEL.CLIP.IMAGE_ENCODER.FROZEN = False
_C.MODEL.CLIP.IMAGE_ENCODER.ATTN_EMBED_DIM = 2048
_C.MODEL.CLIP.IMAGE_ENCODER.ATTN_OUTPUT_DIM = 1024
_C.MODEL.CLIP.IMAGE_ENCODER.ATTN_NUM_HEADS = 32
_C.MODEL.CLIP.IMAGE_ENCODER.ROI_HEAD = CN()
_C.MODEL.CLIP.IMAGE_ENCODER.ROI_HEAD.NAME = "SimpleROIHeads"
_C.MODEL.CLIP.IMAGE_ENCODER.ROI_HEAD.IN_FEATURES = ["p2", "p3", "p4", "p5"]
_C.MODEL.CLIP.IMAGE_ENCODER.ROI_HEAD.POOLER_RESOLUTION = 7
_C.MODEL.CLIP.IMAGE_ENCODER.ROI_HEAD.POOLER_TYPE = "ROIAlignV2"
_C.MODEL.CLIP.IMAGE_ENCODER.ROI_HEAD.POOLER_SAMPLING_RATIO = 0
_C.MODEL.CLIP.IMAGE_ENCODER.ROI_HEAD.SMOOTH_L1_BETA = 0
