_BASE_: "../base_rcnn_fpn.yaml"
MODEL:
  META_ARCHITECTURE: "GeneralizedRCNNClip"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  WEIGHTS: 'http://dl.fbaipublicfiles.com/cutler/checkpoints/cutler_cascade_final.pth'
  MASK_ON: True
  CLIP:
    ARCHITECTURE: "ViT-L/14"
    TOPK: 1
    CROP_SCALE: 1.0
    IMAGE_ENCODER:
      ROI_HEAD:
        POOLER_RESOLUTION: 7
  BACKBONE:
    FREEZE_AT: 0
  RESNETS:
    DEPTH: 50
    NORM: "SyncBN"
    STRIDE_IN_1X1: False
  FPN:
    NORM: "SyncBN"
  ROI_BOX_HEAD:
    CLS_AGNOSTIC_BBOX_REG: True
  ROI_HEADS:
    NAME: CustomCascadeROIHeads
    NUM_CLASSES: 1
    SCORE_THRESH_TEST: 0.50
    POSITIVE_FRACTION: 0.25
    USE_DROPLOSS: True
    DROPLOSS_IOU_THRESH: 0.01
  RPN:
    POST_NMS_TOPK_TRAIN: 4000
    NMS_THRESH: 0.65
DATASETS:
  TRAIN: ("imagenet_train",)
  TEST: []
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.00005
  STEPS: (80000,)
  MAX_ITER: 160000
  GAMMA: 0.02
  CLIP_GRADIENTS:
    CLIP_TYPE: norm
    CLIP_VALUE: 1.0
    ENABLED: true
    NORM_TYPE: 2.0
  AMP:
    ENABLED: True
INPUT:
  MIN_SIZE_TRAIN: (240, 320, 480, 640, 672, 704, 736, 768, 800, 1024)
  MAX_SIZE_TRAIN: 1333
  MASK_FORMAT: "bitmask"
  FORMAT: "RGB"
TEST:
  PRECISE_BN:
    ENABLED: True
    NUM_ITER: 200
  DETECTIONS_PER_IMAGE: 100
OUTPUT_DIR: "output/"
