_BASE_: "../base_rcnn_fpn.yaml"
VERSION: 2
INPUT:
  FIXED_INPUT_SIZE: False
  FORMAT: BGR
MODEL:
  META_ARCHITECTURE: "GeneralizedRCNNWithText"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  MASK_ON: True
  RESNETS:
    LAYERS: [3, 4, 6, 3]
  BACKBONE:
    NAME: "build_modified_resnet_fpn_backbone"
    FREEZE_AT: 0
    CONFIG:
      PRETRAINED: False
      OUT_FEATURES:
        - layer1
        - layer2
        - layer3
        - layer4
      STRIDES:
        - 4
        - 8
        - 16
        - 32
      REMAPS:
        - res2
        - res3
        - res4
        - res5
      REMOVE_LAYERS:
        - attnpool
  CLIP:
    IMAGE_ENCODER:
      ATTN_EMBED_DIM: 256
      ATTN_OUTPUT_DIM: 1024
      ATTN_NUM_HEADS: 32
      ROI_HEAD:
        IN_FEATURES: ["p2", "p3", "p4", "p5"]
  ROI_BOX_HEAD:
    CLS_AGNOSTIC_BBOX_REG: True
  ROI_HEADS:
    NAME: CustomCascadeROIHeads
    NUM_CLASSES: &num_classes 1
    SCORE_THRESH_TEST: 0.0
    POSITIVE_FRACTION: 0.25
    USE_DROPLOSS: True
    DROPLOSS_IOU_THRESH: 0.01
  RPN:
    NMS_THRESH: 0.65
    POST_NMS_TOPK_TRAIN: 4000        
DATASETS:
  TRAIN: ["coco_2017_train", ]
  TEST: []
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.00005
  STEPS: (80000,)
  MAX_ITER: 160000
  GAMMA: 0.02
  CLIP_GRADIENTS:
    CLIP_TYPE: norm
    CLIP_VALUE: 1.0
    ENABLED: true
    NORM_TYPE: 2.0
  AMP:
    ENABLED: True
