_BASE_: "../base_rcnn.yaml"
VERSION: 2
INPUT:
  FIXED_INPUT_SIZE: False
MODEL:
  META_ARCHITECTURE: "GeneralizedRCNNWithText"
  MASK_ON: False
  RESNETS:
    LAYERS: [3, 4, 6, 3]
  BACKBONE:
    NAME: "build_modified_resnet_backbone"
    FREEZE_AT: 0
    CONFIG:
      PRETRAINED: False
      OUT_FEATURES:
        - layer4
      STRIDES:
        - 32
      REMAPS:
        - res5
      REMOVE_LAYERS:
        - attnpool
  CLIP:
    IMAGE_ENCODER:
      ATTN_EMBED_DIM: 2048
      ATTN_OUTPUT_DIM: 1024
      ATTN_NUM_HEADS: 32
      ROI_HEAD:
        IN_FEATURES: ["res5"]
  ROI_BOX_HEAD:
    CLS_AGNOSTIC_BBOX_REG: True
  ROI_HEADS:
    NAME: CustomCascadeROIHeads
    NUM_CLASSES: &num_classes 1
    SCORE_THRESH_TEST: 0.0
    POSITIVE_FRACTION: 0.25
    USE_DROPLOSS: True
    DROPLOSS_IOU_THRESH: 0.01
    SCORE_THRESH_TEST: 0.5
  RPN:
    NMS_THRESH: 0.65
    POST_NMS_TOPK_TRAIN: 4000
DATASETS:
  TRAIN: [leaf]
