_BASE_: "../base_rcnn_fpn.yaml"
VERSION: 2
INPUT:
  MAX_SIZE_TRAIN: 1120
  MAX_SIZE_TEST: 1120
  MIN_SIZE_TRAIN:
    - 1120
  MIN_SIZE_TEST: 1120
  FIXED_INPUT_SIZE: true
  MASK_FORMAT: "bitmask"
  FORMAT: BGR
MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  MASK_ON: True
  CLIP:
    IMAGE_ENCODER:
      FROZEN: True
      ATTN_EMBED_DIM: 2048
      ATTN_OUTPUT_DIM: 1024
      ATTN_NUM_HEADS: 32
      ROI_HEAD:
        IN_FEATURES: ["p2", "p3", "p4", "p5"]
    TEXT_ENCODER:
      FROZEN: True
  BACKBONE:
    CONFIG:
      OUT_FEATURES:
        - layers.0.blocks.1
        - layers.1.blocks.1
        - layers.2.blocks.5
        - layers.3.blocks.1
      PRETRAINED: False
      REMAPS:
        - block1
        - block2
        - block3
        - block4
      REMOVE_LAYERS:
        - norm
        - avgpool
        - head
      STRIDES:
        - 4
        - 8
        - 16
        - 32
      CHANNELS:
        - 96
        - 192
        - 384
        - 768
    FREEZE_AT: 0
    NAME: "build_swin_tiny_patch4_window7_224_fpn_backbone"
  ROI_BOX_HEAD:
    CLS_AGNOSTIC_BBOX_REG: True
  ROI_HEADS:
    NAME: "CustomCascadeROIHeads"
    NUM_CLASSES: 1
    SCORE_THRESH_TEST: 0.0
    POSITIVE_FRACTION: 0.25
    USE_DROPLOSS: True
    DROPLOSS_IOU_THRESH: 0.01
    PROPOSAL_APPEND_GT: False
  RPN:
    POST_NMS_TOPK_TRAIN: 4000
    NMS_THRESH: 0.65
  FPN:
    IN_FEATURES:
      - block1
      - block2
      - block3
      - block4
DATASETS:
  TRAIN: ["coco_2017_train", ]
  TEST: []
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.00005
  STEPS: (80000,)
  MAX_ITER: 160000
  GAMMA: 0.02
  CLIP_GRADIENTS:
    CLIP_TYPE: norm
    CLIP_VALUE: 1.0
    ENABLED: true
    NORM_TYPE: 2.0
  AMP:
    ENABLED: True
